### ISSUE TITLE
Error when specifying 'en' in the list of included locales.

### ISSUE THREAD

**Issue by veelci** [makepanic/ember-power-calendar-date-fns#15]
When specifying 'en' in the list of included locales, I'm getting an error:

> Can't resolve 'date-fns/locale/en'

I believe this is because 'en' is used as the default locale for date-fns.  It isn't in the docs for ^2.0.0, but can be found in the [Supported Languages section of the Internationalization docs for v1.30.1](http://date-fns.org/v1.30.1/docs/I18n#supported-languages).

> date-fns currently supports:
> - English (en; it's the built-in language and doesn't require any setup)

### Possible solutions:
* Remove "en" from the example list of supported languages in the docs.
* Skip the import for "en" in index.js

**Comment by makepanic** [comment]
Oops sorry. 
It seems like you're right. They don't have a simple `en` definition in their [locales](https://github.com/date-fns/date-fns/tree/master/src/locale).

**Comment by makepanic** [comment]
I've updated the README.
It seems like the [default locale is `en-US`](https://github.com/date-fns/date-fns/blob/master/src/format/index.js#L2) so you'd have to also specify that in the list of locales, if you only want to include that.

**Comment by veelci** [comment]
Thank you.
