### ISSUE TITLE
Add support for ember-power-calendar > 0.14

### ISSUE THREAD

**Issue by makepanic** [makepanic/ember-power-calendar-date-fns#9]
requires at least ember@3.11, see https://github.com/cibernox/ember-power-calendar/blob/master/CHANGELOG.md#0140

This would be a breaking change

@veelci do you have anything against upgrading to latest ember-power-calendar and dropping support for ember < 3.11?

**Comment by veelci** [comment]
That is fine.  I'm already using the latest version of ember-power-calendar.
